#!/bin/bash

# Default variables
PROJECT_NAME="HelloWorld"
APP_NAME="HelloWorld"
COMPANY_NAME="example"
GRADLE_VERSION=8.2
GRADLE_PLUGIN_VERSION=7.4.2
APP_MIN_SDK=21
APP_TARGET_SDK=33
APP_COMPILE_SDK=33

# Clear the terminal
clear

echo -e "Hello from yantrigo! This script generates the basic android application project structure."
echo "Before proceeding further make sure you have setup ANDROID_HOME enviroment variable and have android-sdk."

read -p "Enter your project name (Default : $PROJECT_NAME): " input_proj_name

if [ -z "$input_proj_name" ]; then
	:
else
	PROJECT_NAME="${input_proj_name// /_}"
fi

echo "Your project is $PROJECT_NAME"

read -p "Enter your app name (Default : $APP_NAME): " input_app_name

if [ -z "$input_app_name" ]; then
	:
else
	APP_NAME="${input_app_name// /_}"
fi

echo "Your app name is $APP_NAME"


read -p "Enter your company name (Default : $COMPANY_NAME): " input_company_name

if [ -z "$input_company_name" ]; then
        :
else
        COMPANY_NAME="${input_company_name// /_}"
fi

echo "Your company name is $COMPANY_NAME"



read -p "Enter gradle version required (Default : $GRADLE_VERSION): " input_gradle_version

if [ -z "$input_gradle_version" ]; then
	:
else
	GRADLE_VERSION="$input_gradle_version"
fi

echo "Your gradle version is $GRADLE_VERSION"


read -p "Enter gradle plugin version required (Default : $GRADLE_PLUGIN_VERSION): " input_gradle_plugin_version

if [ -z "$input_gradle_plugin_version" ]; then
        :  
else
        GRADLE_PLUGIN_VERSION="$input_gradle_plugin_version"
fi

echo "Your gradle plugin version is $GRADLE_PLUGIN_VERSION"


read -p "Enter minimum sdk version (Default : $APP_MIN_SDK): " input_min_sdk

if [ -z "$input_min_sdk" ]; then
        :  
else
        APP_MIN_SDK="$input_min_sdk"
fi

echo "Your min sdk version is $APP_MIN_SDK"


read -p "Enter target sdk version (Default : $APP_TARGET_SDK): " input_min_sdk

if [ -z "$input_target_sdk" ]; then
        :  
else
        APP_TARGET_SDK="$input_target_sdk"
fi

echo "Your target sdk version is $APP_TARGET_SDK"


read -p "Enter compile sdk version (Default : $APP_COMPILE_SDK): " input_min_sdk

if [ -z "$input_compile_sdk" ]; then
        :  
else
        APP_COMPILE_SDK="$input_compile_sdk"
fi

echo "Your compile sdk version is $APP_COMPILE_SDK"


echo "Building folder structure..."

mkdir -p "$PROJECT_NAME"

cd "$PROJECT_NAME" || { echo "Failed to enter project directory"; exit 1; }


../gradlew init --type basic --dsl groovy --project-name "$PROJECT_NAME" --incubating
./gradlew wrapper --gradle-version "$GRADLE_VERSION"

cat > gradle.properties <<EOL
# Enable AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Project-wide properties
APP_NAMESPACE=com.$COMPANY_NAME.$APP_NAME
APP_ID=com.$COMPANY_NAME.$APP_NAME
APP_VERSION_CODE=1
APP_VERSION_NAME=1.0
APP_MIN_SDK=$APP_MIN_SDK
APP_TARGET_SDK=$APP_TARGET_SDK
APP_COMPILE_SDK=$APP_COMPILE_SDK

EOL


cat > build.gradle <<EOL
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$GRADLE_PLUGIN_VERSION"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
EOL

cat > settings.gradle <<EOL
/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.2/userguide/building_swift_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.4.0'
}

rootProject.name = "$PROJECT_NAME"
include('app')
EOL


mkdir -p "./app/src/main/java/com/$COMPANY_NAME/$APP_NAME/"
mkdir -p "./app/src/main/res/layout"

cat > ./app/build.gradle <<EOL
plugins {
    id 'com.android.application'
}

android {
    namespace APP_NAMESPACE
    compileSdk APP_COMPILE_SDK.toInteger()

    defaultConfig {
        applicationId APP_ID
        minSdk APP_MIN_SDK.toInteger()
        targetSdk APP_TARGET_SDK.toInteger()
        versionCode APP_VERSION_CODE.toInteger()
        versionName APP_VERSION_NAME
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}

EOL

APP_LABEL="${APP_NAME//_/ }"
cat > ./app/src/main/AndroidManifest.xml <<EOL
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.$COMPANY_NAME.$APP_NAME">

    <application
        android:allowBackup="true"
        android:label="$APP_LABEL"
        android:theme="@style/Theme.AppCompat.Light.NoActionBar">

        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

    </application>
</manifest>

EOL

cat > ./app/src/main/res/layout/activity_main.xml <<EOL
<LinearLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:gravity="center"
    android:padding="20dp"
>

<TextView
    android:id="@+id/tvMessage"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="This is your $APP_LABEL"
    android:textSize="24sp"
    android:padding="16dp"
/>

</LinearLayout>

EOL

cat > "./app/src/main/java/com/$COMPANY_NAME/$APP_NAME/MainActivity.java" <<EOL
package com.$COMPANY_NAME.$APP_NAME;

import android.os.Bundle;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;

public class MainActivity extends AppCompatActivity{
    private TextView tvMessage;

    @Override
    protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        tvMessage = findViewById(R.id.tvMessage);
        tvMessage.setText("This is your $APP_LABEL");
    }
}
EOL

cd ./app/src/main/res

mkdir -p mipmap-mdpi mipmap-hdpi mipmap-xhdpi mipmap-xxhdpi mipmap-xxxhdpi
